### ISSUE TITLE
first code

### ISSUE THREAD

**Issue by LinguList** [lingpy/workflow-paper#1]
@macyl, please let us make this repository flat, so only the code we want to submit should be added, so it's easier to share it with zenodo. 

Can you make a first suggestion by adding the code, along with the tutorial text we have on the online system? I think the tutorial belongs here...

**Comment by Wu-Urbanek** [comment]
My suggestion : 

| Python script | Functions |Manuscript|
| -------------:|:----------|:----------|
| `1_lifting.py`|From raw data to tokenized data| 3.2.1 |
|`1_lifting_example.py`|From raw data to tokenized data, an example to take 25 varieties| tutorial|
| `2_partial.py`|From tokenized data to cognate sets| 3.2.2|
| `3_alignment.py`|From cognate sets to alignments| 3.2.3 |
| `4_crosssemantic.py`|From alignments to cross-semantic cognates| 3.2.4|
| `5_correspondence.py`|From ross-semantic cognates to sound correspondence patterns| 3.2.5|
| `P_validate.py` | The python script to generate a distance matrix |Discussion|

**Comment by LinguList** [comment]
Yes, we start from that!

**Comment by Wu-Urbanek** [comment]
updated. please have a look
