### ISSUE TITLE
archive and release? 

### ISSUE THREAD

**Issue by Wu-Urbanek** [lingpy/workflow-paper#5]
@LinguList I updated the readme file and uploaded the readme file. The problem is the requirements.txt. I tired to clone the chenhmongmien with this tag :
`git clone https://github.com/lexibank/chenhmongmien.git@ea5af2854c68d96ea2af24ccbcd87b95b1fc185b`
But it didn't work, so I haven't updated the requirements.txt

**Comment by LinguList** [comment]
can't you clone lexibank-chenhmongmien by its version now?

**Comment by LinguList** [comment]
I'm just testing it on a fresh venv. I updated the requirements. Will
push soon.
